apiVersion: v1
kind: Pod

metadata:
  name: node-affinity-demo
  namespace: kuberesue
  labels:
    app: node-affinity-demo

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - scheduled

  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80