apiVersion: v1
kind: Service
metadata:
  name: kuberesue-service
  namespace: kuberesue
spec:
  type: ClusterIP
  selector:
    app: kuberesue-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 
